# hosts.ini.tpl

[jenkins]
jenkins-server ansible_host=18.200.246.67 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devsecops-key

[tools]
tools-server ansible_host=3.255.232.0 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devsecops-key

[monitoring]
monitoring-server ansible_host=34.242.251.63 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devsecops-key

[k8s_master]
k8s-master ansible_host=3.253.22.183 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devsecops-key

[k8s_workers]
k8s-worker-1 ansible_host=54.78.190.37 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devsecops-key
k8s-worker-2 ansible_host=54.78.160.13 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devsecops-key

[k8s:children]
k8s_master
k8s_workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3